# Generated by Django 4.2.3 on 2023-08-15 21:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('starting_date', models.DateField()),
                ('description', models.TextField()),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('number', models.IntegerField(unique=True)),
                (
                    'training_plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='training_plan.trainingplan',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'day_of_the_week',
                    models.CharField(
                        choices=[
                            ('monday', 'Monday'),
                            ('tuesday', 'Tuesday'),
                            ('wednesday', 'Wednesday'),
                            ('thursday', 'Thursday'),
                            ('friday', 'Friday'),
                            ('saturday', 'Saturday'),
                            ('sunday', 'Sunday'),
                        ],
                        max_length=9,
                    ),
                ),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                (
                    'week',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='training_plan.week',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
