# Generated by Django 4.2.3 on 2023-08-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('day_of_the_week', 'week')},
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('training_plan', 'number')},
        ),
    ]
