---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.8"
services:
  db:
    image: "postgres:14-alpine"
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    <<: &web
      image: "eiger:dev"
      build:
        target: development_build
        context: .
        dockerfile: Dockerfile
        args:
          - DJANGO_ENV=development
          - UID=${UID:-1000}
          - GID=${GID:-1000}
        cache_from:
          - "eiger:dev"
          - "eiger:latest"
      ports:
        # We only bind ports directly in development:
        - "8000:8000"
      volumes:
        - .:/code
      env_file: .env
      environment:
        DJANGO_DATABASE_HOST: db
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_started
    command: bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python -Wd manage.py runserver 0.0.0.0:8000"
    container_name: web
    healthcheck:
      # We use `$$` here because:
      # one `$` goes to shell,
      # one `$` goes to `docker-compose.yaml` escaping
      test: |
        /usr/bin/test $$(
          /usr/bin/curl --fail http://localhost:8000/healthcheck/?format=json
          --write-out "%{http_code}" --silent --output /dev/null
        ) -eq 200
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ci:
    <<: *web
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_started
    ports: [ ]
    command: ./scripts/ci.sh

  tests:
    <<: *web
    depends_on:
      db:
        condition: service_healthy
    ports: [ ]
    command: ./scripts/tests.sh
    stdin_open: true
    tty: true

  mutation-tests:
    <<: *web
    ports: [ ]
    command: ./scripts/mutation-tests.sh

  formatter:
    <<: *web
    ports: [ ]
    command: ./scripts/formatter.sh

  web-prd:
    <<: *web
    image: "eiger:latest"
    depends_on:
      nginx:
        condition: service_started
      db:
        condition: service_healthy
    build:
      target: production_build
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_ENV=production
      cache_from:
        - "eiger:dev"
        - "eiger:latest"
    volumes:
      - static_volume:/var/www/django/static
      - media_volume:/var/www/django/media
    command: ./scripts/gunicorn.sh
    restart: unless-stopped
    networks:
      - web-prd-network
    healthcheck:
      # We use `$$` here because:
      # one `$` goes to shell,
      # one `$` goes to `docker-compose.yaml` escaping
      test: |
        /usr/bin/test $$(
          /usr/bin/curl --fail http://localhost:8000/healthcheck/?format=json
          --write-out "%{http_code}" --silent --output /dev/null
        ) -eq 200
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_volume:/var/www/django/static
      - media_volume:/var/www/django/media
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - web-prd-network

  functional-tests:
    <<: *web
    image: "eiger:latest"
    build:
      target: production_build
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_ENV=development
      cache_from:
        - "eiger:latest"
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_started
    command: ./scripts/functional-tests.sh
    restart: unless-stopped

  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
      - 7900:7900

networks:
  web-prd-network:
volumes:
  media_volume:
  static_volume:
