# fly.toml file generated for eiger on 2023-07-05T22:20:23-03:00

app = "eiger"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DOMAIN_NAME = "eiger.fly.dev, 172.19.132.34"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/healthcheck/?format=json"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
