# Generated by Django 4.2.3 on 2023-08-21 01:29

import uuid

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='The name of the category.',
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    'color',
                    colorfield.fields.ColorField(
                        default='#FFFFFF',
                        help_text='The color that represents the category.',
                        image_field=None,
                        max_length=18,
                        samples=[
                            ('#FF5722', 'deep orange'),
                            ('#5BC0EB', 'teal'),
                            ('#FFB33A', 'light yellow'),
                            ('#4CAF50', 'lime'),
                        ],
                    ),
                ),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='The name of the exercise type.',
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        help_text=(
                            'The category to which this exercise type belongs.'
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to='trainers.category',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Exercise Type',
                'verbose_name_plural': 'Exercise Types',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True,
                        help_text='The name of the exercise.',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, help_text='A description of the exercise.'
                    ),
                ),
                (
                    'reviewed',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Indicates whether the exercise has been reviewed.'
                        ),
                    ),
                ),
                (
                    'should_have_time',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Indicates whether time under effort should be'
                            ' added to this exercise.'
                        ),
                    ),
                ),
                (
                    'should_have_repetition',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Indicates whether repetitions should be added to'
                            ' this exercise.'
                        ),
                    ),
                ),
                (
                    'should_add_weight',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Indicates whether weight should be added to this'
                            ' exercise.'
                        ),
                    ),
                ),
                (
                    'is_test',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Indicates whether this exercise is a test for a'
                            ' specific metric.'
                        ),
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        help_text='The user who created the exercise.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sub_category',
                    models.ForeignKey(
                        help_text='The type of exercise.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='trainers.subcategory',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(
                fields=('category', 'name'), name='unique_sub_categories'
            ),
        ),
    ]
