# Generated by Django 4.2.2 on 2023-07-02 15:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(
                default='#FFFFFF',
                help_text='The color that represents the category.',
                image_field=None,
                max_length=18,
                samples=[
                    ('#FF5722', 'deep orange'),
                    ('#5BC0EB', 'teal'),
                    ('#FFB33A', 'light yellow'),
                    ('#4CAF50', 'lime'),
                ],
            ),
        ),
    ]
