# Generated by Django 4.2.3 on 2023-08-15 21:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_plan', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPE',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('scale', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('display_text', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('sets', models.PositiveSmallIntegerField(default=1)),
                (
                    'target_repetitions',
                    models.PositiveSmallIntegerField(null=True),
                ),
                (
                    'target_time_in_seconds',
                    models.PositiveSmallIntegerField(null=True),
                ),
                (
                    'target_time_unit',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('minutes', 'Minutes'),
                            ('seconds', 'Seconds'),
                        ],
                        max_length=7,
                    ),
                ),
                ('target_weight', models.PositiveSmallIntegerField(null=True)),
                (
                    'day',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='training_plan.day',
                    ),
                ),
                (
                    'exercise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='trainers.exercise',
                    ),
                ),
                (
                    'target_rpe',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='workout.rpe',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedWorkout',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'completed_percentage',
                    models.PositiveSmallIntegerField(null=True),
                ),
                ('notes', models.TextField(blank=True)),
                (
                    'perceived_rpe',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='completed_workouts',
                        to='workout.rpe',
                    ),
                ),
                (
                    'workout',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='workout.workout',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
