# Generated by Django 4.2.3 on 2023-08-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='target_rpe',
        ),
    ]
