# Generated by Django 4.2.3 on 2023-08-21 01:29

import uuid

import django.db.models.deletion
from django.db import migrations, models

import eiger.moonboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('grade', models.CharField(db_index=True, max_length=4)),
                (
                    'setter_user_id',
                    models.CharField(blank=True, max_length=36),
                ),
                ('setter_name', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(max_length=255)),
                (
                    'user_rating',
                    models.PositiveSmallIntegerField(db_index=True),
                ),
                ('repeats', models.PositiveIntegerField(db_index=True)),
                ('is_benchmark', models.BooleanField(db_index=True)),
                ('is_master', models.BooleanField()),
                ('upgraded', models.BooleanField()),
                ('downgraded', models.BooleanField()),
                ('api_id', models.PositiveIntegerField()),
                ('date_inserted', models.DateTimeField()),
                ('date_updated', models.DateTimeField(null=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('has_beta_video', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoldSetup',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                ('angle', models.CharField(max_length=2)),
                ('api_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'hold',
                    models.CharField(
                        db_index=True,
                        max_length=3,
                        validators=[eiger.moonboard.models.validate_hold],
                    ),
                ),
                ('is_start', models.BooleanField()),
                ('is_end', models.BooleanField()),
                (
                    'boulder',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='moves',
                        to='moonboard.boulder',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_climbed', models.DateTimeField()),
                ('comment', models.TextField()),
                ('user_grade', models.CharField(max_length=4)),
                ('attempts', models.CharField(max_length=20)),
                (
                    'boulder',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='completed_boulders',
                        to='moonboard.boulder',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='completed_boulders',
                        to='authentication.climber',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='boulder',
            name='hold_setup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='boulders',
                to='moonboard.holdsetup',
            ),
        ),
        migrations.CreateModel(
            name='AccountData',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                (
                    'climber',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='authentication.climber',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
