# Generated by Django 4.2.3 on 2023-08-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbookentry',
            old_name='user',
            new_name='climber',
        ),
    ]
