# Generated by Django 4.2.3 on 2023-08-15 21:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetric',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                ('workout_id', models.UUIDField()),
                ('value', models.CharField(max_length=255)),
                (
                    'metric_type',
                    models.CharField(
                        choices=[
                            ('hangboard_max_weight', 'Hangboard Max Weight'),
                            ('hangboard_min_edge', 'Hangboard Min Edge'),
                            ('weighted_pull_ups', 'Weighted Pull-ups'),
                            (
                                'max_flash_boulder_grade',
                                'Max Flash Boulder Grade',
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseMetricType',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'metric_type',
                    models.CharField(
                        choices=[
                            ('hangboard_max_weight', 'Hangboard Max Weight'),
                            ('hangboard_min_edge', 'Hangboard Min Edge'),
                            ('weighted_pull_ups', 'Weighted Pull-ups'),
                            (
                                'max_flash_boulder_grade',
                                'Max Flash Boulder Grade',
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    'exercise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exercise_metric_types',
                        to='trainers.exercise',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
