# Generated by Django 4.2.3 on 2023-08-21 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        ('workout', '0001_initial'),
        ('metric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeundereffortmetric',
            name='workout',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='workout.workout',
            ),
        ),
        migrations.AddField(
            model_name='fingerstrengthmetricconfiguration',
            name='exercise',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='finger_strength_metric_configuration',
                to='trainers.exercise',
            ),
        ),
        migrations.AddField(
            model_name='fingerstrengthmetric',
            name='workout',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='workout.workout',
            ),
        ),
        migrations.AddField(
            model_name='exercisemetrictype',
            name='exercise',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='exercise_metric_types',
                to='trainers.exercise',
            ),
        ),
        migrations.AddField(
            model_name='climbermetric',
            name='workout',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='workout.workout',
            ),
        ),
    ]
