# Generated by Django 4.2.3 on 2023-08-21 22:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
        ('metric', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeundereffortmetricconfiguration',
            name='identifier',
            field=models.SlugField(
                choices=[
                    ('lactate-curve-test', 'Lactate Curve Test'),
                    ('hollow-body-hold-test', 'Hollow Body Hold Test'),
                    ('rfd-test', 'Rate of Force Development Test'),
                ]
            ),
        ),
        migrations.CreateModel(
            name='RateOfForceDevelopmentMetric',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'arm_protocol',
                    models.CharField(
                        choices=[
                            ('one_arm', 'One Arm'),
                            ('two_arms', 'Two Arms'),
                        ],
                        max_length=20,
                    ),
                ),
                ('weight_in_kilos', models.IntegerField(default=0)),
                (
                    'grip_type',
                    models.CharField(
                        choices=[
                            ('sloper', 'Sloper'),
                            ('pinch', 'Pinch'),
                            ('full-crimp', 'Crimp'),
                            ('open-hand', 'Open Hand'),
                            ('half-crimp', 'Half Crimp'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'edge_size_in_millimeters',
                    models.PositiveSmallIntegerField(default=20),
                ),
                ('set', models.PositiveSmallIntegerField(default=1)),
                (
                    'maximum_repetitions',
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    'workout',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='workout.workout',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
