# Generated by Django 4.2.3 on 2023-08-21 22:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        (
            'metric',
            '0003_alter_timeundereffortmetricconfiguration_identifier_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeundereffortmetricconfiguration',
            name='identifier',
            field=models.SlugField(
                choices=[
                    ('lactate-curve-test', 'Lactate Curve Test'),
                    ('hollow-body-hold-test', 'Hollow Body Hold Test'),
                ]
            ),
        ),
        migrations.CreateModel(
            name='RateOfForceDevelopmentConfiguration',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='The timestamp when the object was created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'The timestamp when the object was last updated.'
                        ),
                    ),
                ),
                (
                    'exercise',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rfd_metric_configuration',
                        to='trainers.exercise',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
