name: CI
run-name: ${{ github.actor }} is Running CI
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
      - main

env:
  REGISTRY: "cloud.canister.io:5000"
  PROJECT_NAME: "eiger"
  GROUP_NAME: "abxsantos"
  IMAGE_FULL_NAME: "${REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker registry
        run: |
          docker login -u "${{ secrets.REGISTRY_USER }}" -p "${{ secrets.REGISTRY_PASSWORD }}" "cloud.canister.io:5000"

      - name: Build and run tests
        run: |
          docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1 --progress=plain web
          docker-compose up ci

      - name: Check image size
        run: |
          docker image inspect "${{ env.PROJECT_NAME }}:dev" --format='{{.Size}}'

      - name: Push image to registry
        run: |
          docker tag "${{ env.PROJECT_NAME }}:dev" "${{ env.IMAGE_FULL_NAME }}:dev"
          docker push "${{ env.IMAGE_FULL_NAME }}:dev"

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_report
          path: coverage.xml
