name: Deploy
run-name: ${{ github.actor }} is Running Deploy
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    branches:
      - main


env:
  REGISTRY: "cloud.canister.io:5000"
  PROJECT_NAME: "eiger"
  GROUP_NAME: "abxsantos"
  IMAGE_FULL_NAME: "${REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker registry
        run: |
          docker login -u "${{ secrets.REGISTRY_USER }}" -p "${{ secrets.REGISTRY_PASSWORD }}" "${REGISTRY}"

      - name: Build web-prd service
        run: |
          docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1 --progress=plain web-prd

      - name: Check image size
        run: |
          docker image inspect "${PROJECT_NAME}:latest" --format='{{.Size}}'

      - name: Push image to registry
        run: |
          docker tag "${PROJECT_NAME}:latest" "${IMAGE_FULL_NAME}:${{ github.sha }}"
          docker push "${IMAGE_FULL_NAME}:${{ github.sha }}"

      - name: Deploy to fly.io
        uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: deploy --config ./fly.toml --local-only --image "${IMAGE_FULL_NAME}:${{ github.sha }}"
