# Based on https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
name: Release
run-name: ${{ github.actor }} is running Release
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

env:
  REGISTRY: "cloud.canister.io:5000"
  PROJECT_NAME: "eiger"
  GROUP_NAME: "abxsantos"
  IMAGE_FULL_NAME: "${REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}"

jobs:

  deploy:
    name: Deploy to fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo ::set-output name=tag::${TAG}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker registry
        run: |
          docker login -u "${{ secrets.REGISTRY_USER }}" -p "${{ secrets.REGISTRY_PASSWORD }}" "cloud.canister.io:5000"

      - name: Check image size
        run: |
          docker image inspect "${{ env.PROJECT_NAME }}:dev" --format='{{.Size}}'

      - name: Push image to registry
        run: |
          docker tag "${{ env.PROJECT_NAME }}:${{ steps.prep.outputs.tag }}" "${{ env.IMAGE_FULL_NAME }}:${{ steps.prep.outputs.tag }}"
          docker push "${{ env.IMAGE_FULL_NAME }}:${{ steps.prep.outputs.tag }}"

      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: deploy --config ./fly.toml --image ${{ env.IMAGE_FULL_NAME }}:${{ steps.prep.outputs.tag }}

  release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Semantic Release
        run: |
          pip install python-semantic-release
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish
